export const images = {
    welcome1: require('../../assets/img/welcome1.png'),
    welcome2: require('../../assets/img/welcome2.png'),
    welcome3: require('../../assets/img/welcome3.png'),
    bar1: require('../../assets/img/bar1.png'),
    bar2: require('../../assets/img/bar2.png'),
    bar3: require('../../assets/img/bar3.png'),
    bar4: require('../../assets/img/bar4.png'),
    bar5: require('../../assets/img/bar5.png'),
    bar6: require('../../assets/img/bar6.png'),
    bar7: require('../../assets/img/bar7.png'),
    bar8: require('../../assets/img/bar8.png'),
    bar9: require('../../assets/img/bar9.png'),
    bar10: require('../../assets/img/bar10.png'),
    bar11: require('../../assets/img/bar11.png'),
    loveRecipeAIBg: require('../../assets/img/LoveRecipeAIBg.png'),
    congratulations: require('../../assets/img/Congratulations.png'),
    exampleScreen: require('../../assets/img/ExampleScreen.png'),
    example1: require('../../assets/img/example1.png'),
    example2: require('../../assets/img/example2.jpeg'),
    createAccount: require('../../assets/img/CreateAccount.png'),
    add: require('../../assets/img/add.png'),
};
